### ISSUE TITLE
Do we need to distinguish infinite lengths from unknown lengths?

### ISSUE THREAD

**Issue by ssfrr** [haberdashPI/SignalBase.jl#1]
Can you clarify what situations you'd want to differentiate between a known-infinite vs. an unknown length signal? It would be simpler if we just represented both of them as `missing`, but maybe there are places where it's useful to distinguish them.

**Comment by haberdashPI** [comment]
The distinction arises when combining signals `A` and `B`, such as during `mix`: the resulting signal is as long as the longest finite length signal.

If `A` is length `N`, and `B `is missing, then `mix(A,B)` is length `missing`, but if `B` is length `inflen` then `mix(A,B)` is length `N`. (Well ideally, my simple implementation currently fails for the `missing` case and succeeds for the `inflen` case).

**Comment by ssfrr** [comment]
I would think that mixing with an infinite-length signal would give you another infinite-length signal, so `mix(osc1, osc2)` would give an infinite-length signal, and `mix(sig, osc)` would give an infinite-length signal where the beginning of it is also mixed with `sig`. Also then the rule for `mix` is just that the returned value is as long as the longest argument (which could be infinite).

I think I'd lean towards making that more explicit, and if you're using an infinite-length source like an oscillator you'd need to specify how much of it you want to grab to mix with your other signal.

So to mix a finite-length signal `sig` with an oscillator `osc` it would be something like `mix(sig, take(osc, length(sig)))` (where `take` is the iterator function that takes a certain number of samples from a (possibly infinite) generator). Then `missing` could just mean "an unknown, and possibly infinite length" and we wouldn't need a separate `inflen` type.

It could also be written as `take(mix(osc, sig), length(sig))`, which I think would be equivalent.

Though also I think that these sorts of semantic decisions don't need to be be made from within SignalBase (unless it becomes clear they would be useful). I'd argue we should put the very minimal set of things in SignalBase, and keep anything that requires real design thought inside of other packages and move things into SignalBase as interoperability is required.

**Comment by haberdashPI** [comment]
Ah, yes, I see now how what I described is kind of an obscure and idiosyncratic example: the reason this makes sense for `mix` and friends is that you want to be able to pad things without specifying that we pad until the end of the longest signal. E.g. `mix(pad(x,one),y)` does not yield an infinite signal, even though `pad(x,one)` is infinite. Ultimately though that is perhaps a question of taste, and yeah, I agree, probably orthogonal to the concerns of `SignalBase`.

Another point occurred to me though: unlike `missing`, `inflen` can resolve to a non-missing value. For example `min(10,inflen) == 10`. This is useful when writing any code that reasons about the lengths of signals because you don't have to special case the infinite values, you can just apply the logic you would want to apply in the finite-signal case. In contrast, if you want to reason about an arbitrary length signal, you can't safely assume as much, e.g. `ismissing(min(10,missing))`

**Comment by haberdashPI** [comment]
One thing I do wonder about, is whether I should really treat `missing` values as finite. It is more convenient for my implementation of `SignalOperators` that `missing` is treated as finite, but I think it would be more semantically coherent to treat `missing` as possibly infinite.

**Comment by ssfrr** [comment]
I see the convenience for those examples, but it's not clear that it's the only way someone would want things to work, i.e. whether a hypothetical `mix` function should default to padding the shorter signal or truncating the longer one isn't super clear to me.

> Another point occurred to me though: unlike missing, inflen can resolve to a non-missing value. For example min(10,inflen) == 10. This is useful when writing any code that reasons about the lengths of signals because you don't have to special case the infinite values, you can just apply the logic you would want to apply in the finite-signal case.

But in SignalOperators you are special-casing `inflen`, right? I would expect operations involving `inflen` signals to be the limiting case of operations with length-L signals as L approaches infinity. From what I understand of the SignalOperators semantics (e.g. `mix`), the result is the length of the longest finite operand.

I think an `inflen` type seems like it has some valid use-cases, but I'm not sure it needs to live in SignalBase. It might actually make sense to put it in an Infinity.jl package for anyone who wants to have a `Number` type that represents a typed infinity.

So my vote would be to remove `inflen` (or move it into SignalOperators or a separate package). On the one hand it's not doing any harm here, but it seems like extra complexity in code and semantics that I'm not sure is worth it. I would argue that SignalBase should have the minimal set of things to support shared features or functions between packages, but currently we don't have multiple packages that want to use `inflen` independently (unless you maybe have others that you want SignalBase to bridge between).

> I think it would be more semantically coherent to treat `missing` as possibly infinite.

This is a good point. For instance if you're reading a signal from an IO stream, you don't know whether it's a file (finite-length) or maybe some kind of network stream or something.

**Comment by haberdashPI** [comment]
> But in SignalOperators you are special-casing inflen, right?

In several places for reasoning about the lengths of signals I can just apply the logic of `min`, `max` etc.. and worry about whether it is infinite later, which reduces the boilerplate.

> I think an `inflen` type seems like it has some valid use-cases, but I'm not sure it needs to live in SignalBase. 

Fair enough, `inflen` isn't necessarily specific to signals. And actually, now that I'm looking, there is *already* a package called [Infinity.jl](https://github.com/cjdoris/Infinity.jl) which looks like it does what I want. Hah!

If I get this correctly, it seems like we can both agree that there are some more general cases for `nffames` to return `missing`, but `inflen` (or `Infinite` from [Infinity.jl](https://github.com/cjdoris/Infinity.jl)) is maybe more specific to `SignalOperators`. 

Seems like there are two options. 

1. Just document that `nframes` returns the number of frames, period. 
2. Document that the number might be a `missing` value, in the case of a stream. 

I think the 2 is probably better, to avoid surprises, but could also see a case for keeping it really simple in this package.

**Comment by ssfrr** [comment]
I'm on-board with #2. For the record I also have no problems with`SignalOperators` returning `inflen` or similar as a length - I don't think we need a rigorous spec, just a shared place to put some functions.
