### ISSUE TITLE
Give example of `channeltype`

### ISSUE THREAD

**Issue by ssfrr** [haberdashPI/SignalBase.jl#2]
Similarly to #1, can you give an example of when the `channeltype` would be different from `eltype`?

**Comment by haberdashPI** [comment]
This arises most concretely for objects that aren't arrays. For example, filestreams don't have `eltype` defined, but `channeltype` could be defined for a particular kind of file stream. 

Another example would be an array of `Tuple` values. We might want to define `channeltype` as follows

```julia
channeltype(x::Vector{<:NTuple{<:Any,T}}) where T = T
```

Whereas the eltype is a `Tuple` type.

**Comment by ssfrr** [comment]
So it’s for a situation where the object is iterable so it has `eltype` defined, but it doesn’t iterate over individual samples? What do you think about `sampletype` as a name for this?

**Comment by haberdashPI** [comment]
Ah yes, I like `sampletype`, seems good to me.
